#!/usr/bin/env ruby

if ARGV[0]
begin
	Dir.chdir(ARGV[0])
rescue
	puts "No such directory `#{ARGV[0]}'"
	exit
end
end

unless Dir.entries('.').include? "Checklist"
	puts "No `Checklist' file found in directory"
	exit
end

files = Dir.entries('.') - ["Checklist",".",".."]

list = File.read("Checklist").split(/\n/).map {|x| x = x.split(/\./)[0] }
files.map! {|x| x = x.split(/\./)[0] }
list-= files
list.delete ""
list.delete nil
if list.count > 0
print "The follwing files are missing:\n\t*\t"
puts list.join("\n\t*\t")
else
puts "All files in implementation are accounted for"
end
